package pl.droidevs.books.firebase.auth.responses;

public enum Error {
    WRONG_PASSWORD, EMAIL_ALREADY_USED, WEAK_PASSWORD, LOGIN_FAILED, RESET_PASSWORD_ERROR, USER_NOT_LOGGED_IN, DEVELOPER_ERROR, VERIFICATION_EMAIL_SENDING_ERROR, EMPTY_EMAIL, EMPTY_PHONE_NUMBER
}
